"""Screen layout and tuning for the lane-based dodge game."""

WIDTH = 720
HEIGHT = 960
FPS = 60

LANE_COUNT = 3
# 越大路面越窄、路侧越宽，便于布置景物、降低「整条都是路」的占比。
LANE_MARGIN_X = 220

# Colors (R, G, B) — UI / overlays (road is drawn in realistic_art)
COLOR_BG = (26, 30, 34)
COLOR_UI = (248, 249, 250)
COLOR_UI_DIM = (173, 181, 189)

PLAYER_Y_FRAC = 0.82
# Taller hitbox for forward-running pose (legs extend).
PLAYER_SIZE = (50, 70)

# Real seconds for a full day–night cycle (game time).
DAY_CYCLE_SEC = 110.0

TRAIN_WIDTH = 60
TRAIN_MIN_HEIGHT = 140
TRAIN_MAX_HEIGHT = 220
TRAIN_BASE_SPEED = 6.0
TRAIN_SPEED_DISTANCE_FACTOR = 0.30

SPAWN_START_INTERVAL_MS = 1600
SPAWN_MIN_INTERVAL_MS = 600
SPAWN_DISTANCE_SHRINK = 0.5

# 货车 speed 为「每帧像素」；累计同样数值换算成奔跑米数。
METERS_PER_SPEED_PIXEL = 1.0 / 55.0

# 每跑过多少米切换到下一场景（循环：城郊→沙漠→海岸）。
SCENE_SEGMENT_METERS = 160.0

JUMP_DURATION = 0.45
JUMP_HEIGHT = 100
JUMP_COOLDOWN = 0.25
SLIDE_DURATION = 0.50
SLIDE_COOLDOWN = 0.25

OBSTACLE_WIDTH = 60
OBSTACLE_LOW_HEIGHT = 42
OBSTACLE_HIGH_HEIGHT = 110
OBSTACLE_HIGH_GAP = 50
OBSTACLE_SPAWN_MIN_S = 2.5
OBSTACLE_SPAWN_MAX_S = 5.0
OBSTACLE_SPAWN_MIN_FLOOR_S = 1.8
OBSTACLE_SPAWN_MAX_FLOOR_S = 3.0
OBSTACLE_DISTANCE_SHRINK = 0.0004
OBSTACLE_LANE_COOLDOWN_S = 1.8
OBSTACLE_MIN_Y_GAP = 160
COIN_OBSTACLE_MIN_Y = 90
TRAIN_OBSTACLE_MIN_Y = 140
TRAIN_COIN_MIN_Y = 130
TRAIN_LANE_COOLDOWN_S = 1.2
